name: Builds
on: [push, pull_request]
jobs:
  build-windows-release:
    runs-on: windows-latest
    steps:
      - name: Install correct version of mingw
        run: |
          choco uninstall mingw --force
          choco uninstall strawberryperl --force
      - uses: numworks/setup-msys2@v1
        with:
          msystem: MINGW64
      - run: pip install jinja2
      - uses: humbletim/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-query-version: 1.3.243.0
          vulkan-components: Vulkan-Headers, Vulkan-Loader
          vulkan-use-cache: true
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: cmake .
        env:
          CC: gcc
          CXX: g++
      - run: cmake --build . --config Release
        env:
          CC: gcc
          CXX: g++
