name: Builds
on: [ push, pull_request ]
jobs:
  build-windows-release:
    runs-on: windows-latest
    steps:
      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.1.1
        with:
          version: 1.3.243.0
          cache: true
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ .
      - run: cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ --build . --config Release
